name: mnsf

channels:
  - conda-forge

dependencies:
  - python=3.10
  - anndata=0.8.0
  - click
  - matplotlib
  - numpy
  - pandas
  - pip
  - scanpy
  - squidpy=1.2.2
  - tensorflow=2.13
  - tensorflow-probability=0.21
  - pip:
      - -e .
