name: mnsf

channels:
  - conda-forge

dependencies:
  - python=3.9.10
  - anndata
  - click
  - matplotlib
  - numpy
  - pandas
  - pip
  - scanpy
  - squidpy
  - tensorflow>=2.11
  - tensorflow-probability=0.22.1
  - pip:
      - -e .
