name: mnsf

channels:
  - conda-forge

dependencies:
  - python=3.10
  - anndata
  - click
  - matplotlib
  - numpy
  - pandas
  - pip
  - scanpy
  - squidpy
  - tensorflow=2.13
  - tensorflow-probability=0.21
  - pip:
      - -e .
