name: Run Data prep

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  release:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      #   - name: Install Conda environment
      #     uses: mamba-org/provision-with-micromamba@main
      #     with:
      #       cache-downloads: true
      #       cache-env: true
      #       environment-file: environment.yml
      #       environment-name: mnsf
      - name: Install & test
        run: |
          pip install -e .
        #   pytest
